name: zeive_pos
description: The Zeive POS on the web with Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^3.0.0
  cupertino_icons: ^0.1.2
  equatable: ^1.0.3
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700